---

- name: Template iptables config
  become: true
  template:
    src: iptables.sh.j2
    dest: /root/iptables.sh
  when: iptables is defined
  with_items:
    - "{{ iptables }}"

- name: Execute iptables.sh
  become: true
  shell: bash /root/iptables.sh

- name: Remove iptables.sh
  file:
    path: /root/iptables.sh
    state: absent
