---

- name: Create needed groups
  group:
    name: "{{ item[1] }}"
    state: present
  when: vars['create_'+item[0].username] | default([])
  with_subelements:
    - "{{ users | default([]) }}"
    - groups
    - skip_missing: yes

- name: Create host specific groups
  group:
    name: "{{ item[1] }}"
    state: present
  when: vars['create_'+item[0].username] | default([])
  with_subelements:
    - "{{ users | default([]) }}"
    - "{{ ansible_hostname+'_groups' }}"
    - skip_missing: yes

- name: Create user groups
  group:
    name: "{{ item.usergroup }}"
    state: present
  when: vars['create_'+item.username] | default([])
  loop: "{{ users | default([]) }}"

- name: Add users
  user:
    name: "{{ item.username }}"
    comment: "{{ item.comment | default }}"
    group: "{{ item.usergroup }}"
    groups: "{{ item.groups | default(omit) }}"
    shell: "{{ item.shell }}"
  when: vars['create_'+item.username] | default([])
  loop: "{{ users | default([]) }}"

- name: Add pubkeys to users
  authorized_key:
    user: "{{ item[0].username }}"
    state: present
    key: "{{ item[1] }}"
  when: vars['create_'+item[0].username] | default([])
  with_subelements:
    - "{{ users | default([]) }}"
    - pubkeys
    - skip_missing: yes
