---

- name: Upgrading all packages to latest version
  apt:
    update_cache: yes
    upgrade: dist

- name: Install required packages
  apt:
    name: "{{ packages }}"

- name: Install additional packages for specific host
  apt:
    name: "{{ additional_packages }}"
  when: additional_packages is defined
