---

- name: Becoming root for "basic_config" role
  become: true
  block:
  - include: apt.yml

- name: Set hostname
  become: true
  hostname:
    name: "{{ server_hostname }}"
  when: server_hostname is defined
