---

- name: Install wireguard
  apt:
    name: wireguard
    state: present

- name: Generate missing pubkeys
  shell: echo {{ item.wg_privkey }} | wg pubkey
  register: stdout_pubkeys_servers
  with_items:
    - "{{ vpns }}"

- name: Create directory for client configurations
  file:
    path: /etc/wireguard/clients/{{ item.wg_interface }}
    state: directory
  with_items:
    - "{{ vpns }}"

- name: Create missing public keys for clients
  shell: echo {{ item.privkey }} | wg pubkey
  register: stdout_pubkeys_clients
  with_items:
    - "{{ clients }}"
  when: item.pubkey is undefined

- debug:
    var: stdout_pubkeys_clients

- name: Template server config
  template:
    src: server.j2
    dest: "/etc/wireguard/{{ item.wg_interface }}.conf"
  with_items:
    - "{{ vpns }}"

- name: Create client configs
  template:
    src: client.j2
    dest: "/etc/wireguard/clients/{{ item.vpn }}/{{ item.client }}.conf"
  with_items:
    - "{{ clients }}"

- name: Enable WireGuard service for configured servers
  systemd:
    name: wg-quick@{{ item.wg_interface }}.service
    enabled: yes
    state: started
  with_items:
  - "{{ vpns }}"
